# Generated by Django 5.2.6 on 2026-01-06 12:28

import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'ordering': ['-add_date', 'friendly_token']},
        ),
        migrations.AddField(
            model_name='channel',
            name='logo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='userlogos/user.jpg', upload_to='userlogos/%Y/%m/%d'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['-add_date', 'friendly_token'], name='users_chann_add_dat_acc3d4_idx'),
        ),
    ]
