# Generated by Django 5.2.6 on 2026-01-14 16:12

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_channel_options_channel_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='banner_logo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='userlogos/banner.jpg', upload_to='userlogos/%Y/%m/%d'),
        ),
    ]
