# Generated by Django 5.2.6 on 2026-02-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0015_remove_media_channel_media_channels'),
        ('users', '0004_user_banner_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='select one or more out of the existing tags', to='files.tag'),
        ),
    ]
