# Generated by Django 5.2.6 on 2026-02-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0015_remove_media_channel_media_channels'),
        ('users', '0005_channel_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='category',
            field=models.ManyToManyField(blank=True, help_text='Channel can be part of one or more categories', to='files.category'),
        ),
    ]
