# Generated by Django 5.2.6 on 2026-02-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_channel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='friendly_token',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
