# Generated by Django 5.2.6 on 2026-02-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_channel_friendly_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='friendly_token',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
