# Generated by Django 5.2.6 on 2026-01-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0014_alter_subtitle_options_and_more'),
        ('users', '0004_user_banner_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='channel',
        ),
        migrations.AddField(
            model_name='media',
            name='channels',
            field=models.ManyToManyField(blank=True, help_text='Media can exist in multiple Channels', related_name='media_items', to='users.channel'),
        ),
    ]
