# Generated by Django 5.2.6 on 2026-02-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0015_remove_media_channel_media_channels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='friendly_token',
            field=models.SlugField(blank=True, help_text='Identifier for the Media', max_length=150, unique=True),
        ),
    ]
