# Generated by Django 5.2.6 on 2026-02-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0016_alter_media_friendly_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='friendly_token',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
